/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as OnderzoekWhfbRouteImport } from './routes/onderzoek-whfb'
import { Route as PresentatieRouteImport } from './routes/presentatie'
import { Route as ProtocollenRouteImport } from './routes/protocollen'
import { Route as QuantumRouteImport } from './routes/quantum'
import { Route as ScorekaartRouteImport } from './routes/scorekaart'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as VerdedigingRouteImport } from './routes/verdediging'
import { Route as MfaIndexRouteImport } from './routes/mfa.index'
import { Route as MfaIdRouteImport } from './routes/mfa.$id'
import { Route as ProtocollenIndexRouteImport } from './routes/protocollen.index'
import { Route as ProtocollenIdRouteImport } from './routes/protocollen.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderzoekWhfbRoute = OnderzoekWhfbRouteImport.update({
  id: '/onderzoek-whfb',
  path: '/onderzoek-whfb',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentatieRoute = PresentatieRouteImport.update({
  id: '/presentatie',
  path: '/presentatie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocollenRoute = ProtocollenRouteImport.update({
  id: '/protocollen',
  path: '/protocollen',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumRoute = QuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorekaartRoute = ScorekaartRouteImport.update({
  id: '/scorekaart',
  path: '/scorekaart',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdedigingRoute = VerdedigingRouteImport.update({
  id: '/verdediging',
  path: '/verdediging',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaIndexRoute = MfaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MfaRoute,
} as any)
const MfaIdRoute = MfaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MfaRoute,
} as any)
const ProtocollenIndexRoute = ProtocollenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtocollenRoute,
} as any)
const ProtocollenIdRoute = ProtocollenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtocollenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/mfa': typeof MfaRouteWithChildren
  '/onderzoek-whfb': typeof OnderzoekWhfbRoute
  '/presentatie': typeof PresentatieRoute
  '/protocollen': typeof ProtocollenRouteWithChildren
  '/quantum': typeof QuantumRoute
  '/scorekaart': typeof ScorekaartRoute
  '/tokens': typeof TokensRoute
  '/verdediging': typeof VerdedigingRoute
  '/mfa/$id': typeof MfaIdRoute
  '/protocollen/$id': typeof ProtocollenIdRoute
  '/mfa/': typeof MfaIndexRoute
  '/protocollen/': typeof ProtocollenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/onderzoek-whfb': typeof OnderzoekWhfbRoute
  '/presentatie': typeof PresentatieRoute
  '/quantum': typeof QuantumRoute
  '/scorekaart': typeof ScorekaartRoute
  '/tokens': typeof TokensRoute
  '/verdediging': typeof VerdedigingRoute
  '/mfa/$id': typeof MfaIdRoute
  '/protocollen/$id': typeof ProtocollenIdRoute
  '/mfa': typeof MfaIndexRoute
  '/protocollen': typeof ProtocollenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/mfa': typeof MfaRouteWithChildren
  '/onderzoek-whfb': typeof OnderzoekWhfbRoute
  '/presentatie': typeof PresentatieRoute
  '/protocollen': typeof ProtocollenRouteWithChildren
  '/quantum': typeof QuantumRoute
  '/scorekaart': typeof ScorekaartRoute
  '/tokens': typeof TokensRoute
  '/verdediging': typeof VerdedigingRoute
  '/mfa/$id': typeof MfaIdRoute
  '/protocollen/$id': typeof ProtocollenIdRoute
  '/mfa/': typeof MfaIndexRoute
  '/protocollen/': typeof ProtocollenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/mfa'
    | '/onderzoek-whfb'
    | '/presentatie'
    | '/protocollen'
    | '/quantum'
    | '/scorekaart'
    | '/tokens'
    | '/verdediging'
    | '/mfa/$id'
    | '/protocollen/$id'
    | '/mfa/'
    | '/protocollen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab'
    | '/onderzoek-whfb'
    | '/presentatie'
    | '/quantum'
    | '/scorekaart'
    | '/tokens'
    | '/verdediging'
    | '/mfa/$id'
    | '/protocollen/$id'
    | '/mfa'
    | '/protocollen'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/mfa'
    | '/onderzoek-whfb'
    | '/presentatie'
    | '/protocollen'
    | '/quantum'
    | '/scorekaart'
    | '/tokens'
    | '/verdediging'
    | '/mfa/$id'
    | '/protocollen/$id'
    | '/mfa/'
    | '/protocollen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRoute
  MfaRoute: typeof MfaRouteWithChildren
  OnderzoekWhfbRoute: typeof OnderzoekWhfbRoute
  PresentatieRoute: typeof PresentatieRoute
  ProtocollenRoute: typeof ProtocollenRouteWithChildren
  QuantumRoute: typeof QuantumRoute
  ScorekaartRoute: typeof ScorekaartRoute
  TokensRoute: typeof TokensRoute
  VerdedigingRoute: typeof VerdedigingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onderzoek-whfb': {
      id: '/onderzoek-whfb'
      path: '/onderzoek-whfb'
      fullPath: '/onderzoek-whfb'
      preLoaderRoute: typeof OnderzoekWhfbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentatie': {
      id: '/presentatie'
      path: '/presentatie'
      fullPath: '/presentatie'
      preLoaderRoute: typeof PresentatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocollen': {
      id: '/protocollen'
      path: '/protocollen'
      fullPath: '/protocollen'
      preLoaderRoute: typeof ProtocollenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum': {
      id: '/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof QuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorekaart': {
      id: '/scorekaart'
      path: '/scorekaart'
      fullPath: '/scorekaart'
      preLoaderRoute: typeof ScorekaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdediging': {
      id: '/verdediging'
      path: '/verdediging'
      fullPath: '/verdediging'
      preLoaderRoute: typeof VerdedigingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/': {
      id: '/mfa/'
      path: '/'
      fullPath: '/mfa/'
      preLoaderRoute: typeof MfaIndexRouteImport
      parentRoute: typeof MfaRoute
    }
    '/mfa/$id': {
      id: '/mfa/$id'
      path: '/$id'
      fullPath: '/mfa/$id'
      preLoaderRoute: typeof MfaIdRouteImport
      parentRoute: typeof MfaRoute
    }
    '/protocollen/': {
      id: '/protocollen/'
      path: '/'
      fullPath: '/protocollen/'
      preLoaderRoute: typeof ProtocollenIndexRouteImport
      parentRoute: typeof ProtocollenRoute
    }
    '/protocollen/$id': {
      id: '/protocollen/$id'
      path: '/$id'
      fullPath: '/protocollen/$id'
      preLoaderRoute: typeof ProtocollenIdRouteImport
      parentRoute: typeof ProtocollenRoute
    }
  }
}

interface MfaRouteChildren {
  MfaIdRoute: typeof MfaIdRoute
  MfaIndexRoute: typeof MfaIndexRoute
}

const MfaRouteChildren: MfaRouteChildren = {
  MfaIdRoute: MfaIdRoute,
  MfaIndexRoute: MfaIndexRoute,
}

const MfaRouteWithChildren = MfaRoute._addFileChildren(MfaRouteChildren)

interface ProtocollenRouteChildren {
  ProtocollenIdRoute: typeof ProtocollenIdRoute
  ProtocollenIndexRoute: typeof ProtocollenIndexRoute
}

const ProtocollenRouteChildren: ProtocollenRouteChildren = {
  ProtocollenIdRoute: ProtocollenIdRoute,
  ProtocollenIndexRoute: ProtocollenIndexRoute,
}

const ProtocollenRouteWithChildren = ProtocollenRoute._addFileChildren(
  ProtocollenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRoute,
  MfaRoute: MfaRouteWithChildren,
  OnderzoekWhfbRoute: OnderzoekWhfbRoute,
  PresentatieRoute: PresentatieRoute,
  ProtocollenRoute: ProtocollenRouteWithChildren,
  QuantumRoute: QuantumRoute,
  ScorekaartRoute: ScorekaartRoute,
  TokensRoute: TokensRoute,
  VerdedigingRoute: VerdedigingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
